server:
  port: 9999
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql:///hrms?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  type-aliases-package: org.java.entity